### ISSUE TITLE
Wrong xrefs in ProteinReference

### ISSUE THREAD

**Issue by ozgunbabur** [PathwayCommons/cpath2#224]
Found a bug in the xrefs of some ProteinReference of v8. Look at the PR with ID 

http://purl.org/pc2/8/Protein_84cb92e17a9f567f5456a46088aa57e1

It is related to the gene PANK2, and it has the xref [db:HGNC Symbol, id: PANK2], just as expected. 

But it also have the xref [db: HGNC, id: HGNC:8598], and the xref [db: HGNC, id: HGNC:19365]. The first one belongs to PANK1 and the second one belongs to PANK3.

That is not new to v8. It existed in v7 too.

**Comment by IgorRodchenkov** [comment]
Good catch, not a trivial thing.., and it's unclear what to do.

The Protein (from ReconX) has no xrefs, but the corresponding
ProteinReference
<http://webservice.baderlab.org:48080/get?uri=http://identifiers.org/uniprot/Q9BZ23>
(http://identifiers.org/uniprot/Q9BZ23) has got multiple xrefs (comes
originally from each original PR mapped to this primary UniProt one).

Indeed, the PR has HGNC:8598 and HGNC:19365 rel. xrefs (looks they come
from KEGG: RelationshipXref_kegg_hsa_hsa00770_translatedHGNC_19365_2,
RelationshipXref_kegg_hsa_hsa00770_translatedHGNC_8598_2) - that map to
different primary UniProt ACs
<http://webservice.baderlab.org:48080/idmapping?id=HGNC:8598&id=HGNC:19365&id=HGNC:15894>
...

When Merger "decides" to replace an original PR with the one from the
warehouse, it also then copies all the xrefs from the original PR to the
canonical one.
So, despite we take care not to replace a PR unless it uniquely maps to
only one UniProt AC, in the above case, we created confusion or mess...
If we'd not have copied the xrefs, we'd have lost all original ones
always...

*More details*.
What happens is that e.g., KEGG hsa_00770 has a PR like (and the
corresponding Protein also has these same xrefs, by the way),
which is hard to tell what it means...:

<bp:ProteinReference rdf:about="#hsa53354_hsa55229_hsa79646_hsa80025.eref">
 <bp:name rdf:datatype = "http://www.w3.org/2001/XMLSchema#string
">PANK4</bp:name>
 <bp:name rdf:datatype = "http://www.w3.org/2001/XMLSchema#string
">PANK2</bp:name>
 <bp:name rdf:datatype = "http://www.w3.org/2001/XMLSchema#string
">HSS</bp:name>
 <bp:name rdf:datatype = "http://www.w3.org/2001/XMLSchema#string
">PANK3</bp:name>
 <bp:name rdf:datatype = "http://www.w3.org/2001/XMLSchema#string
">PKAN</bp:name>
 <bp:name rdf:datatype = "http://www.w3.org/2001/XMLSchema#string
">HARP</bp:name>
 <bp:name rdf:datatype = "http://www.w3.org/2001/XMLSchema#string
">PANK1</bp:name>
 <bp:name rdf:datatype = "http://www.w3.org/2001/XMLSchema#string
">C20orf48</bp:name>
 <bp:name rdf:datatype = "http://www.w3.org/2001/XMLSchema#string
">NBIA1</bp:name>
 <bp:xref rdf:resource="UniProt_AC_Q9BZ23_2" />
 <bp:xref rdf:resource="EC_code_27133_2" />
 <bp:xref rdf:resource="OMIM_606160_2" />
 <bp:xref rdf:resource="HGNC:8598_2" />
 <bp:xref rdf:resource="UniProt_AC_Q9NVE7_2" />
 <bp:xref rdf:resource="EntrezGene_80025_2" />
 <bp:xref rdf:resource="Ensembl_ENSG00000152782_2" />
 <bp:xref rdf:resource="HGNC:19366_2" />
 <bp:xref rdf:resource="HGNC:15894_2" />
 <bp:xref rdf:resource="KEGG_Reaction_R02971_2" />
 <bp:xref rdf:resource="HGNC:19365_2" />
 <bp:xref rdf:resource="EntrezGene_79646_2" />
 <bp:xref rdf:resource="Ensembl_ENSG00000125779_2" />
 <bp:xref rdf:resource="EntrezGene_53354_2" />
 <bp:xref rdf:resource="KEGG_Genes_hsa53354_2" />
 <bp:xref rdf:resource="EntrezGene_55229_2" />
 <bp:xref rdf:resource="KEGG_Genes_hsa79646_2" />
 <bp:xref rdf:resource="OMIM_606157_2" />
 <bp:xref rdf:resource="KEGG_Genes_hsa55229_2" />
 <bp:xref rdf:resource="KEGG_Genes_hsa80025_2" />
 <bp:xref rdf:resource="OMIM_606161_2" />
 <bp:xref rdf:resource="UniProt_AC_Q9H999_2" />
 <bp:xref rdf:resource="UniProt_AC_Q6P1K9_1" />
 <bp:xref rdf:resource="UniProt_AC_Q8TE04_2" />
 <bp:xref rdf:resource="Ensembl_ENSG00000157881_2" />
 <bp:xref rdf:resource="OMIM_606162_2" />
 <bp:displayName rdf:datatype = "http://www.w3.org/2001/XMLSchema#string
">PANK</bp:displayName>
 <bp:standardName rdf:datatype =
"http://www.w3.org/2001/XMLSchema#string">PANK1,
MGC24596, PANK, PANK1a, PANK1b...</bp:standardName>
 <bp:organism rdf:resource="Homo_sapiens_human" />
</bp:ProteinReference>

I suspect they (either KEGG db's or KEGGTranslator tool's authors) meant a
generic PR; i.e., there must be separate memberEntityReferences for each
PANK*, etc...

That PR, passing the Normalizer, becomes:
<bp:ProteinReference rdf:about="http://identifiers.org/uniprot/Q6P1K9">
 <bp:name rdf:datatype = "http://www.w3.org/2001/XMLSchema#string
">NBIA1</bp:name>
 <bp:name rdf:datatype = "http://www.w3.org/2001/XMLSchema#string
">HSS</bp:name>
 <bp:name rdf:datatype = "http://www.w3.org/2001/XMLSchema#string
">HARP</bp:name>
 <bp:name rdf:datatype = "http://www.w3.org/2001/XMLSchema#string
">PKAN</bp:name>
 <bp:name rdf:datatype = "http://www.w3.org/2001/XMLSchema#string
">PANK4</bp:name>
...
- The Normalizer cannot check if the unification xrefs are consistent, and
simply picks the first valid one (sorted by id alphabetically) - Q6P1K9
(which, in fact, does not map to any PC2 warehouse primary UniProt AC
ProteinReference, because Q6P1K9 is an "Unreviewed" entry, it's not in the
Swiss-Prot human dataset that we use...).

So, when it comes to merging KEGG into the PC2 main model, the normalized
Q6P1K9 PR, using all its unification xrefs, maps uniquely to the Q9BZ23 PR
in the warehouse and thus gets replaced. The xrefs are also copied to the
canonical Q9BZ23 PR, which is used by proteins from several other data
sources (CTD, ReconX, etc.). And this is how/why we get the issue reported
by Ozgun.

A simple fix (in the Merger) would be - skip replacing such PRs (i.e., also
check if id-mapping using all the unification and rel. xrefs results in the
same unique UniProt AC or nothing). A more tricky fix would be to replace
such PRs with a generic PR and multiple member PRs in a KEGG Cleaner, but
this would require much re-factoring and using a separate id-mapper
(otherwise, it's impossible to re-construct a generic PR and members from
that original messy PR)...

PS:
I am getting tired of such terrible pathway data...
Looks, we'd better never merge anything at all (never merge
EntityReference) but just store original/normalized data as is. Perhaps
just enrich with more xrefs using id-mapping for full-text search and
patterns to work... This is similar to what we actually did in PC1 (
pathwaycommons.org/pc/).

Cheers,
Igor.

**Comment by IgorRodchenkov** [comment]
Now fixing (in the biopax-validator Normalizer, KeggCleanerImpl, and cPath2 Merger)...

**Comment by IgorRodchenkov** [comment]
Oops, looks, I found the bug in the PC2 Merger (in idMappingByXrefsIntersection method), - the true reason why e.g. "hsa53354_hsa55229_hsa79646_hsa80025.eref" PR merges into canonical "Q9B223" despite id-mapping by xrefs is ambiguous (it must not merge!)
Fixing now...
