### ISSUE TITLE
Wikipathways filtering id is inconsistent

### ISSUE THREAD

**Issue by mj3cheun** [PathwayCommons/cpath2#265]
The wikipathways identifier is `wp`. Yet, the only name which is accepted when filtering search results is `wikipathways`. In my opinion, the names accepted for search filtering should be changed to accept both tokens.

**Comment by IgorRodchenkov** [comment]
Hi Manfred, all,

*Nope*,

"wp" is just our internal metadata identifier (and we do not encourage
anyone to use these via api,
because there can be values, e.g.: 'intact', 'intact_complex', 'wp1',
'wp2', 'wp3', 'reactome_mouse' now or in the future - depends how we
prepare and import data into PC...).

*However*, the /*search* query  accepts absolute URIs as 'datasource'
filter values as well, i.e.:

http://beta.pathwaycommons.org/pc2/search?q=*&type=pathway&datasource=http://pathwaycommons.org/pc2/wp


(*note*: URL query parameters after /search? must be URL-encoded, though it
sometimes works as is in browsers);
but then, if you'd filter by the 'intact' URI you'd miss 'intact_complex'...

Although filtering by URI works now for all sources but Intact the same way
if you'd use corresponding standard name, I strongly do not recommend using
URI there...
(one can even do like datasource=w* but I would not recommend ;))

*Therefore,*
we want users *search by data provider's name*, which every data
portion/chunk behind the scene has, despite having different URIs.

Igor R.

**Comment by IgorRodchenkov** [comment]
On Tue, Apr 4, 2017 at 5:27 PM, Igo R <rodche@gmail.com> wrote:

> datasource=w*


Correction: no, you cannot do: datasource=w* (wildcard filter values)

**Comment by mj3cheun** [comment]
Ok thanks, will switch from using id to name.
