### ISSUE TITLE
datasource icon urls might still use http

### ISSUE THREAD

**Issue by d2fong** [PathwayCommons/cpath2#282]
Hi Igor,
I think datasource icon urls might still be using http instead of https, is that intended or should they be served over https?

For example, in the cpath2-client code for getting datasources here:
https://github.com/PathwayCommons/cpath2-client/blob/master/src/datasources.js#L39

An example url returned in the search app is:

http://pathwaycommons.github.io/cpath2/logos/reactome.png

Thanks,
Dylan

**Comment by IgorRodchenkov** [comment]
Dylan, these particular cases are not so important (easy to fix because logo urls are configured via app's properties file, and also can be manually updated later after PC release.. I can do this..). 
But yes, we do have so called mixed content problem with most PC services, and that's not trivial - uneasy to fix even if I update links in the source code, etc... That's why we keep both http and https access.

**Comment by d2fong** [comment]
Okay, just checking.  Thanks.
