### ISSUE TITLE
Extended SIF PubMed IDs column: Source(s)

### ISSUE THREAD

**Issue by jvwong** [PathwayCommons/cpath2#314]
The data in `EXTENDED_BINARY_SIF` format, served from [(beta) SIFGraph service](https://beta.pathwaycommons.org/sifgraph/swagger-ui.html) contains a column for PubMed IDs (section 1, column 5).

For example, the [neighbourhood of TLN1](https://beta.pathwaycommons.org/sifgraph/v1/neighborhood?direction=BOTHSTREAM&limit=1&source=TLN1&pattern=CONTROLS_STATE_CHANGE_OF&pattern=CONTROLS_PHOSPHORYLATION_OF&pattern=CONTROLS_TRANSPORT_OF&pattern=CONTROLS_EXPRESSION_OF&pattern=IN_COMPLEX_WITH&pattern=CATALYSIS_PRECEDES&pattern=INTERACTS_WITH&pattern=NEIGHBOR_OF&pattern=CONSUMPTION_CONTROLLED_BY&pattern=CONTROLS_PRODUCTION_OF&pattern=CONTROLS_TRANSPORT_OF_CHEMICAL&pattern=CHEMICAL_AFFECTS&pattern=REACTS_WITH&pattern=USED_TO_PRODUCE)  outputs:

```...
SIRT7	interacts-with	TLN1	BioGRID	22586326		http://pathwaycommons.org/pc13/MolecularInteraction_37c9957e-9ead-4e5f-96d0-670284d6d247___null__86182_
...
ELF1	controls-expression-of	TLN1	MSigDB			http://pathwaycommons.org/pc13/TemplateReactionRegulation_d7aa58d38362a28444d8151192413cee;http://pathwaycommons.org/pc13/TemplateReaction_b4d560bcfc2e59fef106f19a7dada50c
KANK1	interacts-with	TLN1	Biofactoid		Talin-KANK1 interaction controls the recruitment of cortical microtubule stabilizing complexes to focal adhesions.	http://pathwaycommons.org/pc13/MolecularInteraction_635a5bb6bc9090144a4d3fd44ce76095
 ...
```

Looks like in a lot of cases the PubMed IDs are drawn from BioPAX `bp:Evidence` attached to the interaction. I wonder if:

1. Would a `bp:PublicationXref` directly attached to an interaction end up in the extended SIF? Or is it being exclusively drawn from `bp:Evidence`?
2. If #1 is true generally(not only Evidence): Is it justified to attach a Biofactoid entry's PubMed ID (the one already attached to the `bp:Pathway`) to the constituent  interactions  as a `bp:PublicationXref` in BioPAX? (I guess we won't really have anything approaching `bp:Evidence` from Biofactoid)

The real reason I ask is because the app-ui interaction app will retrieve the PMID-associated paper info, but this currently won't happen for Biofactoid-derived data:

<img width="500" alt="Screen Shot 2022-06-29 at 2 31 07 PM" src="https://user-images.githubusercontent.com/4706307/176510121-335c52db-0738-4b33-91ec-23a914e5df4e.png">

**Comment by IgorRodchenkov** [comment]
@jvwong , I dived into our code and found the following:
- cpath2/pc2 web controllers use BiopaxConverter class, calls `ExtendedSIFWriter.write` in case 'TXT' (extended SIF) format was requested;
- with `ExtendedSIFWriter.write` (in Paxtools/pattern module) it all comes to calling private method: `SIFInteraction.harvestPublicationXrefs(mediators)`; see also `OutputColumn.getColumnValue`; "mediators" are interactions (perhaps can be complexes too), their URIs are listed at the end of each extended SIF line (in the first, interactions section);
- `harvestPublicationXrefs` collects all the PublicationXref objects - BOTH from each mediator interaction's and its evidence's bp:xref properties;
- finally, we only use/print the PUBMED IDs to the output, because `ExtendedSIFWriter.write` also uses `CustomFormat` object (is `SIFToText` interface, stt var.) that explicitely specifies that xref.db must be "pubmed".

Hope it helps. Ask @ozgunbabur too.
